### PR TITLE
Add macos-version-min flag

### LINKED ISSUE #30: Fix linked C symbols on old macOS versions
I've compiled `webrtc-audio-processing` from build machine being Apple M1. It runs fine on the build machine (macOS Ventura). But when running on host `x86_64-darwin-apple` with an older version of macOS (Big Sur) it crashes with the `Missing symbol` error. 

I believe it can be fixed with a similar patch:
https://github.com/h4llow3En/mac-notification-sys/commit/1944fb3245bc1ed7efbed0e0ac49841b8b1f3276

Going to test this solution tomorrow at the office where I have the older Mac and report back. 
Are you open to a PR for this?

### PR DESCRIPTION
**Pull request by morajabi**
Fixes #30

Let's start here, let me know what should I fix/make better. This is my first time messing with Rust custom build script and cc :)

### CODE REVIEW

**Comment by bschwind** [comment]
Thanks for the PR! If you could add build/test instructions, I can run this on the machines I have:

* Intel Macbook Pro 2014 - Big Sur 11.6.2
* M1 Mac Mini - Big Sur 11.7.0
* M1 Macbook Pro - Monterey 12.6.0

**Comment by morajabi** [comment]
So I'm using `webrtc-audio-processing` crate in a Rust macOS application built with [Tauri](https://tauri.app).

This is a build from the branch `master` of this repo. This should crash on startup with the error below:
- DMG for x86_64: [Noor_0.0.38_x64.dmg.zip](https://github.com/tonarino/webrtc-audio-processing/files/10165846/Noor_0.0.38_x64.dmg.zip)
The error: 
Screenshot 2022-12-06 at 13 10 20

So after this patch, I no longer the error and app loads normally to its login screen. The correct build:
- DMG for aarch64 (M1/M2): [Noor_0.0.41_x64.dmg.zip](https://github.com/tonarino/webrtc-audio-processing/files/10165866/Noor_0.0.41_x64.dmg.zip)

I can make a minimum failing case later in a public repo, but I'm a bit busy atm. Basically all you need to do is to load the `webrtc-audio-processing` crate in the `main.rs` of a bare minimum tauri app and build for macOS. It's one command: `npm tauri build --target x86_64-apple-darwin`.

**Comment by morajabi** [comment]
Alright, I made a minimal failing example here: https://github.com/morajabi/wap-example

**Comment by bschwind** [comment]
Thanks for the example, @morajabi

So just to be clear, to test this properly I should build `wap-example` on an _M1 Machine_  with `npm tauri build --target x86_64-apple-darwin`, and then try to run that built application on an intel machine?

**Comment by morajabi** [comment]
My pleasure @bschwind 

That is correct. I suggest building (running the build command) on this machine of yours:
- M1 Macbook Pro - Monterey 12.6.0
And trying to run the binary on this one:
- Intel Macbook Pro 2014 - Big Sur 11.6.2

It should crash using the `master` branch of `webrtc-audio-processing`. If this was the case, change the dependency to `there-so:fix/missing-symbol` from the `Cargo.toml`, then `cargo update` and build again. This one should run without an issue and show a window.

**Comment by bschwind** [comment]
Hmmm, this is a bit mysterious. With no modifications to your example repo, I was able to build with:

```
yarn tauri build --target x86_64-apple-darwin
```

(various invocations of `npm` was giving me issues so I tried `yarn` and it worked)

I built on the M1 Pro machine, received a `wap-example.app` file, transferred it to the Intel machine, and it was able to run just fine. I suspect maybe the compiler stripped the webrtc code out completely.

I added some code to print some stats so that the code isn't stripped:

```rust
fn main() {
    let config = InitializationConfig {
        num_capture_channels: 0,
        ..InitializationConfig::default()
    };
    let p = Processor::new(&config).unwrap();
    dbg!(p.get_stats());
    tauri::Builder::default()
        .invoke_handler(tauri::generate_handler![greet])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
```

And now the app doesn't open on the Intel mac.

However, I update the dependency as you said but it still has the same behavior of not opening on the intel machine.

Actually, with the modifications of preventing the compiler from stripping the `webrtc` code, I can no longer open it on the M1 machine either (which should have no problem running it through Rosetta I believe)

Not sure if I'm doing something wrong but I think I'm not getting the same behavior as you.

> P.S. Yesterday I read your custom keyboard post on Reddit, it was so cool :)

Awww thanks! I'm working on making a better version of it, with support for different case styles. Hoping to get that out soon :)

**Comment by morajabi** [comment]
@bschwind Did you make sure to do `cargo update` and check the `Cargo.lock` to make sure it has picked up the new branch? Cause in my case a simple `cargo build` (tauri build) never updated the branch in Cargo.lock thus the build was using whatever it was using before changing your `Cargo.toml`.

**Comment by bschwind** [comment]
I did run `cargo update` in between builds after changing the dependency but I'll try it again tomorrow morning and report back.

**Comment by morajabi** [comment]
Now I think it comes down to our difference in our M1 machine's macOS version. I've built on Ventura, but you're building on Monterey. I suspect Ventura uses a newer libc++ or something by default, so it isn't compatible with macOS Big Sur.
If you want, we can do a quick screen-share over Zoom and I build a version and send to you so you see me doing the build (to eliminate the security risk for you).

**Comment by bschwind** [comment]
> I've built on Ventura, but you're building on Monterey

Ahhh, that's probably it. I don't think a call is necessary though, if you've witnessed this change fixing it for you I think we can go ahead and merge it. I was just trying to recreate the issue if I could, but the change itself seems plenty low risk that I'm okay with it as-is.

**Comment by morajabi** [comment]
Yes, it does indeed fix it for me. I will keep monitoring as well, you can wait a bit longer until [our alpha launch](https://noor.to) in a couple of days and we can try more widely.

**Comment by bschwind** [comment]
@morajabi how has the launch gone so far?

**Comment by morajabi** [comment]
@bschwind Intel users did not report any crash so far!

**Pull request merged**
