### PR TITLE
Make webrtc-audio-processing API more ideomatic. Includes some other

### PR DESCRIPTION
**Pull request by skywhale**
minor API improvements:

- Moving AEC-related parameters into EchoCancellation
- Fixing the enum name of DigitalFixed -> FixedDigital

### CODE REVIEW

**Comment by skywhale** [comment]
Need to fix tests and samples first

**Comment by skywhale** [comment]
This is ready for a review @mcginty

**Comment by skywhale** [comment]
@mcginty onegaishimasu

**Comment by bschwind** [comment]
Oh one note though! We should probably make `set_config` take a mutable reference to indicate we're changing the processor.

**Comment by skywhale** [comment]
Good idea @bschwind regarding the set_config :)

**Pull request merged**
