### PR TITLE
Release 0.1.2.

### PR DESCRIPTION
**Pull request by skywhale**
Changes:
 - Added support for GainControl::Mode.

### CODE REVIEW

**Comment by skywhale** [comment]
@mcginty おねがいしゃす！

**Comment by bschwind** [comment]
Does `audio-processing-webrtc-sys` also need to be updated?

**Comment by mcginty** [comment]
good catch @bschwind - it actually looks like the gain control changes are only in -sys?

**Comment by skywhale** [comment]
I'm sorry for leaving this PR for long. PTAL

**Comment by skywhale** [comment]
Pushed to crates.io

**Comment by skywhale** [comment]
Should I have incremented the minor version as this changes the API? @mcginty @bschwind

**Comment by bschwind** [comment]
It wasn't a breaking change, right?

We're in version `0.*.*` so changing the minor version actually implies a breaking change. I suppose the patch version would have been incremented in this case.

We're still in unstable territory and I'm not yet sure this crate has any users, so it's probably fine to leave it for now.

**Comment by skywhale** [comment]
It would break if a user wrote `GainControl { <all fields> }`. So I guess technically the minor version should have been incremented. But like you said, not a big deal I guess.

I also realized that `DIGITAL_FIXED` should have been `FIXED_DIGITAL`. Should I fix that and increment the minor version?

**Pull request merged**
